[package]
name = "ebocf"
version = "0.1.0"
edition = "2021"
authors = ["BananaHexagon @g_banana_k"]
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
peg = "0.8.2"
wasm-bindgen = "0.2.90"
